### PR TITLE
Compile for 3ds max 2016

### PR DESCRIPTION
**Pull request by usakhelo**
Hi,

I'm wondering if it is possible to merge this PR into master? I need those changes to compile for 2016 max sdk and I apply them after each master update. It would be very helpful to have them in master.

Changes in PR:

- project and solution files added for 2016
- preprocessor #if-s check against max 2016
- "afxres.h" replaced with "windows.h" to compile without mfc libraries
- NormalizedDiffusionBSSRDFFactory replaced with GaussianBSSRDFFactory because by default appleseed doesn't contain NormalizedDiffusionBSSRDFFactory (at least on my version)

Thanks,
Sergo

### CODE REVIEW

**Comment by dictoon** [comment]
Thanks for the PR! I'll review it tonight.

Regarding this:

> NormalizedDiffusionBSSRDFFactory replaced with GaussianBSSRDFFactory because by default appleseed doesn't contain NormalizedDiffusionBSSRDFFactory (at least on my version)

You need to enable the Normalized Diffusion model when building appleseed by passing `-DWITH_NORMALIZED_DIFFUSION_BSSRDF=ON` to CMake.

**Comment by est77** [comment]
I added a PR to remove the option to disable building ND.
https://github.com/appleseedhq/appleseed/pull/1422

**Comment by usakhelo** [comment]
Restored NormalizedDiffusionBSSRDFFactory

**Comment by dictoon** [comment]
Excellent, thank you!

**Pull request merged**
