### PR TITLE
Several fixes and improvements

### PR DESCRIPTION
**Pull request by dictoon**

### CODE REVIEW

**Comment by usakhelo** [comment]
Hi @dictoon, everything in this PR works and looks fine to me.

**Comment by dictoon** [comment]
Thanks for the review @usakhelo!

**Comment by usakhelo** [comment]
Hi @dictoon ,
Sorry I missed one simple check - something happend to cancellation. I can't cancel the rendering in max 2016 after this PR. I tried to revert "Fix random black tiles bug" commit and cancel worked again.

**Comment by usakhelo** [comment]
I'll file the issue just in case..

**Pull request merged**
